package model

type EquityDataResponse struct {
	AskPx         float64 `json:"ask_px"`
	AskSz         int     `json:"ask_sz"`
	AvgVol30D     int     `json:"avg_vol30d"`
	BidPx         float64 `json:"bid_px"`
	BidSz         int     `json:"bid_sz"`
	ClosingPx     float64 `json:"closing_px"`
	Column        int     `json:"column"`
	ComShrsOut    int     `json:"com_shrs_out"`
	CompDesc      string  `json:"comp_desc"`
	CompName      string  `json:"comp_name"`
	Condition     int     `json:"condition"`
	DivAmt        float64 `json:"div_amt"`
	DivDateEx     string  `json:"div_date_ex"`
	DivYield      float64 `json:"div_yield"`
	High52WPx     float64 `json:"high52w_px"`
	HighPx        float64 `json:"high_px"`
	InfoTime      string  `json:"info_time"`
	IssueMarket   string  `json:"issue_market"`
	IssureMarket  string  `json:"issure_market"`
	LastPx        float64 `json:"last_px"`
	Low52WPx      float64 `json:"low52w_px"`
	LowPx         float64 `json:"low_px"`
	MktCap        int     `json:"mkt_cap"`
	OpenPx        float64 `json:"open_px"`
	PayDate       string  `json:"pay_date"`
	PeRatio       float64 `json:"pe_ratio"`
	PostAskPx     float64 `json:"post_ask_px"`
	PostAskSz     int     `json:"post_ask_sz"`
	PostBidPx     float64 `json:"post_bid_px"`
	PostBidSz     int     `json:"post_bid_sz"`
	PostLastPx    float64 `json:"post_last_px"`
	PostQuoteTime string  `json:"post_quote_time"`
	PostTradeTime string  `json:"post_trade_time"`
	PreAskPx      float64 `json:"pre_ask_px"`
	PreAskSz      int     `json:"pre_ask_sz"`
	PreBidPx      float64 `json:"pre_bid_px"`
	PreBidSz      int     `json:"pre_bid_sz"`
	PreLastPx     float64 `json:"pre_last_px"`
	PreQuoteTime  string  `json:"pre_quote_time"`
	PreTradeTime  string  `json:"pre_trade_time"`
	QuoteTime     string  `json:"quote_time"`
	Symbol        string  `json:"symbol"`
	TradePx       float64 `json:"trade_px"`
	TradeRegion   string  `json:"trade_region"`
	TradeSz       int     `json:"trade_sz"`
	TradeTime     string  `json:"trade_time"`
	Volume        int     `json:"volume"`
	YestClosePx   float64 `json:"yest_close_px"`
}
