package orbis_api

type ScrenerResponse []ScrenerResponseElement

type ScrenerResponseElement struct {
	Quote              QuoteScreener `json:"quote"`
	Etf                EtfScreener   `json:"etf"`
	Value              int64         `json:"value"`
	Option             bool          `json:"option"`
	HasRecentUpgrade   bool          `json:"hasRecentUpgrade"`
	HasRecentDowngrade bool          `json:"hasRecentDowngrade"`
	Symbol             string        `json:"symbol"`
}

type EtfScreener struct {
	Symbol        string  `json:"symbol"`
	SponsorID     int64   `json:"sponsorId"`
	Sponsor       string  `json:"sponsor"`
	SponsorDesc   string  `json:"sponsorDesc"`
	SponsorURL    string  `json:"sponsorUrl"`
	AssetID       int64   `json:"assetId"`
	Asset         string  `json:"asset"`
	CategoryID    int64   `json:"categoryId"`
	Category      string  `json:"category"`
	StructureType string  `json:"structureType"`
	StructureID   int64   `json:"structureId"`
	Structure     string  `json:"structure"`
	InceptionDate string  `json:"inceptionDate"`
	Leverage      int64   `json:"leverage"`
	ExpenseRatio  float64 `json:"expenseRatio"`
	URL           string  `json:"url"`
	FactSheetURL  string  `json:"factSheetUrl"`
	ProspectusURL string  `json:"prospectusUrl"`
	OtherUrls     string  `json:"otherUrls"`
	CountryPct    int64   `json:"countryPct"`
	ContinentPct  int64   `json:"continentPct"`
	SectorCode    int64   `json:"sectorCode"`
	SectorPct     int64   `json:"sectorPct"`
	PriceRank     int64   `json:"priceRank"`
	PriceChange   int64   `json:"priceChange"`
	PriceChange1W int64   `json:"priceChange1w"`
	PriceChange2W int64   `json:"priceChange2w"`
	PriceChange1M int64   `json:"priceChange1m"`
	Exposure      int64   `json:"exposure"`
	Inverse       bool    `json:"inverse"`
	Active        bool    `json:"active"`
	Option        bool    `json:"option"`
}

type QuoteScreener struct {
	Symbol                  string  `json:"symbol"`
	CompanyName             string  `json:"companyName"`
	Isin                    string  `json:"isin"`
	Cusip                   string  `json:"cusip"`
	Sedol                   string  `json:"sedol"`
	Country                 string  `json:"country"`
	Mic                     string  `json:"mic"`
	Currency                string  `json:"currency"`
	Source                  string  `json:"source"`
	IdentType               string  `json:"identType"`
	Exchange                string  `json:"exchange"`
	BidRegion               Region  `json:"bidRegion"`
	AskRegion               Region  `json:"askRegion"`
	TradeRegion             Region  `json:"tradeRegion"`
	UpdateTime              string  `json:"updateTime"`
	TradeTime               string  `json:"tradeTime"`
	CalendarYearHighDate    string  `json:"calendarYearHighDate"`
	CalendarYearLowDate     string  `json:"calendarYearLowDate"`
	Week52HighDate          string  `json:"week52HighDate"`
	Week52LowDate           string  `json:"week52LowDate"`
	Vwap                    float64 `json:"vwap"`
	Vwap1                   int64   `json:"vwap1"`
	YesterdayClose          float64 `json:"yesterdayClose"`
	OpeningPrice            float64 `json:"openingPrice"`
	StrikePrice             int64   `json:"strikePrice"`
	DayHigh                 float64 `json:"dayHigh"`
	DayLow                  float64 `json:"dayLow"`
	Ask                     float64 `json:"ask"`
	Bid                     float64 `json:"bid"`
	AskYield                int64   `json:"askYield"`
	BidYield                int64   `json:"bidYield"`
	LastPrice               float64 `json:"lastPrice"`
	Change                  float64 `json:"change"`
	OpenInterest            int64   `json:"openInterest"`
	High52Week              float64 `json:"high52week"`
	Low52Week               float64 `json:"low52week"`
	PriceEarningRatio       int64   `json:"priceEarningRatio"`
	ChangePercent           float64 `json:"changePercent"`
	MarketCap               float64 `json:"marketCap"`
	CalendarYearHigh        float64 `json:"calendarYearHigh"`
	CalendarYearLow         float64 `json:"calendarYearLow"`
	DividendYield           int64   `json:"dividendYield"`
	DividendAmount          int64   `json:"dividendAmount"`
	DividendRate            int64   `json:"dividendRate"`
	Beta                    float64 `json:"beta"`
	TotalCashAmount         int64   `json:"totalCashAmount"`
	EstimatedCashAmount     int64   `json:"estimatedCashAmount"`
	IntradayValue           int64   `json:"intradayValue"`
	Nav                     int64   `json:"nav"`
	TradePrice              float64 `json:"tradePrice"`
	YesterdayVolume         int64   `json:"yesterdayVolume"`
	AskSize                 int64   `json:"askSize"`
	BidSize                 int64   `json:"bidSize"`
	MinAskSize              int64   `json:"minAskSize"`
	MinBidSize              int64   `json:"minBidSize"`
	Volume                  int64   `json:"volume"`
	ContractSize            int64   `json:"contractSize"`
	AverageVolume30         int64   `json:"averageVolume30"`
	ImbalanceVolume         int64   `json:"imbalanceVolume"`
	SharesOutstanding       int64   `json:"sharesOutstanding"`
	Increment               int64   `json:"increment"`
	TradeSize               int64   `json:"tradeSize"`
	PutOrCall               string  `json:"putOrCall"`
	Indicator               int64   `json:"indicator"`
	SubMarket               int64   `json:"subMarket"`
	BidTick                 int64   `json:"bidTick"`
	Precision               int64   `json:"precision"`
	Delayed                 bool    `json:"delayed"`
	NotFound                bool    `json:"notFound"`
	Option                  bool    `json:"option"`
	NotPermissioned         bool    `json:"notPermissioned"`
	Halted                  bool    `json:"halted"`
	Paused                  bool    `json:"paused"`
	Mini                    bool    `json:"mini"`
	CorpAct                 bool    `json:"corpAct"`
	Jumbo                   bool    `json:"jumbo"`
	MutualFund              bool    `json:"mutualFund"`
	Bond                    bool    `json:"bond"`
	Nbbo                    bool    `json:"nbbo"`
	Crypto                  bool    `json:"crypto"`
	Fx                      bool    `json:"fx"`
	SymbolMarket            string  `json:"symbolMarket"`
	Call                    bool    `json:"call"`
	MarketCapClassification string  `json:"marketCapClassification"`
	DividentSoon            bool    `json:"dividentSoon"`
	SymbolChange            bool    `json:"symbolChange"`
	MarketDescription       string  `json:"marketDescription"`
	AtTheMoney              bool    `json:"atTheMoney"`
	InTheMoney              bool    `json:"inTheMoney"`
	Trailing12MonthsEps     int64   `json:"trailing12MonthsEps"`
	Put                     bool    `json:"put"`
}

type ScreenerRequest struct {
	InverseType    *string  `json:"inverseType"`
	LeverageType   *string  `json:"leverageType"`
	AssetID        *string  `json:"assetId"`
	CategoryID     *string  `json:"categoryId"`
	SponsorID      *string  `json:"sponsorId"`
	Start          *int64   `json:"start"`
	Num            *int64   `json:"num"`
	Sort           *string  `json:"sort"`
	Asc            bool     `json:"asc"`
	LoadIndustries bool     `json:"loadIndustries"`
	LoadUpgrades   bool     `json:"loadUpgrades"`
	LoadEarnings   bool     `json:"loadEarnings"`
	Filters        []string `json:"filters"`
}
